public class Main {
    public static void main(String[] args) {
       //account number, balance, customer name, email, phone number
        //create getters and setter for each field
        //additional method-> one for depositing funds and other for withdrawing funds
        //customer not be allowed withdrawal if it takes balance negative

            Account bobsAccount= new Account("12345",1000.00,"Bob Brown","bob@gmail.com","01789....");

            System.out.println(bobsAccount.getNumber());
            System.out.println(bobsAccount.getBalance());
            bobsAccount.withdrawFunds(100.00);
             bobsAccount.depositFunds(250);
           bobsAccount.withdrawFunds(50);
           bobsAccount.depositFunds(1000);
           bobsAccount.withdrawFunds(1500);
           //constructor overloading
        //default constructor called implicitly
        //Byte Code can be defined as an intermediate code generated by the compiler after the compilation of source code(JAVA Program).
        // This intermediate code makes Java a platform-independent language.

    }
}